name: go test

on: [push, pull_request]

permissions: 
  # TODO
  # Note that since we're automatically formatting ill formatted code
  # on any push as well as pull requests. It might be dangerous to
  # setup write permission on PRs, but maybe not since the write
  # is probably going to happen on the branch where the PR takes
  # is originating from, maybe. Need to make sure.
  contents: write

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      - name: Check out repo
        uses: actions/checkout@v4
      - name: go vet
        # Checks for potentially problematic code not found by compiler   
        # https://pkg.go.dev/cmd/vet
        run: go vet ./...
      - name: go fmt
        run: | 
          go fmt ./...
          # workaround for when git reports the directory as "dubious" ownership
          git config --global --add safe.directory '*'
          # commit changes if any
          git add -u
          if [[ $(git diff HEAD --name-only | wc -l | bc) > 0 ]]; then
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git commit -m 'bot: gofmt'
            git push
          fi
      - name: go test
        run: | 
          # Run go fmt in each directory
          go test ./...
